"""Command-line interface.

  <prog> plan --csv demands.csv --device xc7z020 [options]
  <prog> parse-bit partial1.bit [partial2.bit ...]

The demands CSV carries one row per reconfigurable region, modeled on the
demand table of the FLORA paper (resource requirements per region as
LUT / FF / BRAM / DSP counts) plus an optional trailing ``slices`` column
(measured occupied slices -- report_utilization -pblocks, "Slice" row, on
a routed design):

    name,lut,ff,bram,dsp,slices
    rp0,2874,2026,0,12,1127
    rp1,2972,2026,0,12,1264

The header row is optional; '#' starts a comment.  ``bram`` is in RAMB18
(18 Kb half-block) units -- the unit Vivado HLS/utilization reports count
as BRAM_18K; one RAMB36 = two RAMB18.  Rows without the sixth field get
the ceil(lut/4) perfect-packing default, which a measured placement
failure on the case-study design ([Place 30-487]) shows is optimistic --
prefer
measured slice occupancy (see docs/LIMITS.md item 1).
"""
import argparse
import json
import sys

from . import bitparse, device, emit, milp


def read_demands_csv(path):
    """Parse the demands CSV -> ordered dict name -> demand dict."""
    demands = {}
    with open(path) as f:
        for raw in f:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            fields = [x.strip() for x in line.split(",")]
            if len(fields) not in (5, 6):
                raise ValueError("expected 5 or 6 fields (name,lut,ff,bram,"
                                 "dsp[,slices]), got %d: %r"
                                 % (len(fields), line))
            if not all(x.lstrip("-").isdigit() for x in fields[1:]):
                # header row (or a malformed line found later)
                if not demands:
                    continue
                raise ValueError("non-numeric demand fields: %r" % line)
            name = fields[0]
            if name in demands:
                raise ValueError("duplicate region name %r" % name)
            lut, ff, bram, dsp = (int(x) for x in fields[1:5])
            d = {"lut": lut, "ff": ff, "bram": bram, "dsp": dsp}
            if len(fields) == 6:
                d["slices"] = int(fields[5])
            for label in ("lut", "ff", "bram", "dsp", "slices"):
                if d.get(label, 0) < 0:
                    raise ValueError("negative %s demand for %s"
                                     % (label, name))
            demands[name] = d
    if not demands:
        raise ValueError("no demand rows found in %s" % path)
    return demands


def cmd_plan(args):
    dev = device.load_device(args.device)
    demands = read_demands_csv(args.csv)
    result = milp.solve(dev, demands, objective=args.objective,
                        derate=args.derate, headroom=args.headroom,
                        forbid_specials=args.forbid_specials,
                        static_bram_reserve=args.static_bram,
                        verbose=args.verbose)
    print(json.dumps(result, indent=1))
    regions = [(name, r["ranges"]) for name, r in result["regions"].items()]
    header = ("generated by the '%s' objective, derate %s, headroom %s, "
              "device %s"
              % (args.objective, args.derate, args.headroom, args.device))
    if args.out_pblocks:
        with open(args.out_pblocks, "w") as f:
            f.write(emit.pblocks_text(regions, header=header))
        print("wrote %s" % args.out_pblocks, file=sys.stderr)
    if args.out_xdc:
        cells = {}
        for spec in args.cell or []:
            if "=" not in spec:
                raise SystemExit("--cell expects NAME=HIER/PATH, got %r" % spec)
            name, path = spec.split("=", 1)
            cells[name] = path
        with open(args.out_xdc, "w") as f:
            f.write(emit.xdc_text(regions, cells=cells or None, header=header))
        print("wrote %s" % args.out_xdc, file=sys.stderr)
    if args.out_json:
        with open(args.out_json, "w") as f:
            json.dump(result, f, indent=1)
        print("wrote %s" % args.out_json, file=sys.stderr)
    return 0


def cmd_parse_bit(args):
    rc = 0
    for path in args.files:
        res = bitparse.parse(path)
        if res is None:
            print("%s: no sync word found" % path, file=sys.stderr)
            rc = 1
        else:
            print(bitparse.report(res))
        print()
    return rc


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="MILP floorplanner for FPGA partial reconfiguration "
                    "(open solver: HiGHS)")
    sub = ap.add_subparsers(dest="command", required=True)

    p = sub.add_parser("plan", help="solve a floorplan from a demands CSV")
    p.add_argument("--csv", required=True,
                   help="demands CSV: name,lut,ff,bram,dsp[,slices] per "
                        "region (bram in RAMB18 units; slices = measured "
                        "occupied slices, defaults to the optimistic "
                        "ceil(lut/4) when absent)")
    p.add_argument("--device", default="xc7z020",
                   help="bundled device name or path to a device-model JSON "
                        "(bundled: %s)" % ", ".join(device.list_devices()))
    p.add_argument("--objective", choices=("frames", "wr"), default="frames",
                   help="frames = minimize configuration frames (partial "
                        "bitstream size / reconfig time); wr = FLORA's "
                        "wasted-resources metric")
    p.add_argument("--derate", type=float, default=1.0,
                   help="usable fraction of covered capacity (the user's "
                        "design-margin knob; e.g. 0.5 = 2x headroom)")
    p.add_argument("--headroom", type=float, default=0.93,
                   help="calibrated placement-headroom fraction, multiplied "
                        "with --derate (usable = derate * headroom * "
                        "capacity).  Default 0.93: measured on the case "
                        "study's first hardware build -- +1.1%% netlist "
                        "growth between the demand snapshot and the rebuilt "
                        "netlist (3,005 LUTs assigned vs 2,972 modeled) "
                        "plus placer packing limits.  1.0 disables it")
    p.add_argument("--forbid-specials", action="store_true",
                   help="exclude resource-less special columns (clock spine/"
                        "config) from the regions")
    p.add_argument("--static-bram", type=int, default=0,
                   help="RAMB18 that must remain outside all regions "
                        "(static-design reservation)")
    p.add_argument("--out-pblocks", help="write pblocks.txt-format ranges here")
    p.add_argument("--out-xdc", help="write Vivado XDC constraints here")
    p.add_argument("--out-json", help="write the full result JSON here")
    p.add_argument("--cell", action="append",
                   help="NAME=HIER/PATH cell binding for the XDC output "
                        "(repeatable)")
    p.add_argument("--verbose", action="store_true",
                   help="let the solver log to stdout")
    p.set_defaults(func=cmd_plan)

    p = sub.add_parser("parse-bit",
                       help="parse 7-series partial bitstreams (FAR/FDRI "
                            "frame accounting)")
    p.add_argument("files", nargs="+")
    p.set_defaults(func=cmd_parse_bit)

    args = ap.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
