"""Configuration-frame and partial-bitstream-size accounting.

The model was measured from real xc7z020 partial bitstreams (parsed with
``bitparse.py``) generated by a Vivado 2019.1 Dynamic Function eXchange flow
with RESET_AFTER_RECONFIG:

  * every covered frame region is written TWICE (the shutdown/restore
    command sequence), plus one pad frame per FDRI write;
  * a fixed preamble of ``preamble_frames`` frames is present in every
    partial, independent of the pblock;
  * BRAM columns additionally carry ``bram_content_frames`` content frames
    per column per covered clock-region row (their own FDRI write, again
    doubled, +1 pad per row);
  * bytes = frame_bytes * frames + overhead_bytes, exactly.

For a rectangle R covering columns C and clock-region rows W:

  frames(R) = preamble
            + 2 * (sum_{c in C, r in W} f_type(c)  +  |W|)
            + [ 2 * (bram_content_frames * |bram cells|  +  |bram rows|)
                if R covers any BRAM column ]

This reproduces the case study's two measured partials byte-exactly and
reconciles two further recorded partial sizes to exact integer frame counts
(see tests/test_frames.py).  The original two measured partials are
single-row; the multi-row structure (one FDRI block per covered row) was
later confirmed by a rebuilt 2-row partial (byte-exact) and a 3-row partial
(frame-exact, +64 B of FAR packet overhead where the region crosses the
device's half boundary) -- see docs/LIMITS.md item 6.
"""


def region_frames(device, cols, rows):
    """Frames and bytes of the partial bitstream for a rectangle.

    cols: iterable of covered tile-column X coordinates.
    rows: iterable of covered clock-region rows.
    Returns (frames, bytes).  Raises if the rectangle spans a dead cell.
    """
    cols = sorted(cols)
    rows = sorted(rows)
    f0 = 0
    bram_cells = 0
    bram_rows = set()
    for c in cols:
        col = device.columns[c]
        for r in rows:
            if r not in col["rows"]:
                raise ValueError("cell (%d,%d) has no fabric" % (c, r))
        f0 += device.frames[col["type"]] * len(rows)
        if col["type"] == "BRAM":
            bram_cells += len(rows)
            bram_rows.update(rows)
    frames = device.preamble_frames
    frames += 2 * (f0 + len(rows))
    if bram_cells:
        frames += 2 * (bram_cells * device.bram_content_frames + len(bram_rows))
    return frames, frames * device.frame_bytes + device.overhead_bytes
